import React from 'react'

import {
  listCommands,
  listAvatars,
  getItems,
  getEntities,
  getScenes,
  listQuests,
  getMainQuestFor
} from '@/backend/data'

class PlainText extends React.PureComponent {
  /**
   * Creates a paragraph of commands.
   * @private
   */
  private getCommands(): React.ReactNode {
    return (
      <>
        {listCommands().map(command => (
          <p className={'text-white'} key={command.name[0]}>
            {`${command.name[0]} : ${command.description}`}
          </p>
        ))}
      </>
    )
  }

  /**
   * Creates a paragraph of avatars.
   * @private
   */
  private getAvatars(): React.ReactNode {
    return (
      <>
        {listAvatars()
          .sort((a, b) => a.id - b.id)
          .map(avatar => (
            <p className={'text-white'} key={avatar.id}>
              {`${avatar.id} : ${avatar.name}`}
            </p>
          ))}
      </>
    )
  }

  /**
   * Creates a paragraph of items.
   * @private
   */
  private getItems(): React.ReactNode {
    return (
      <>
        {getItems()
          .sort((a, b) => a.id - b.id)
          .map(item => (
            <p className={'text-white'} key={item.id}>
              {`${item.id} : ${item.name}`}
            </p>
          ))}
      </>
    )
  }

  /**
   * Creates a paragraph of monsters.
   * @private
   */
  private getMonsters(): React.ReactNode {
    return (
      <>
        {getEntities()
          .sort((a, b) => a.id - b.id)
          .map(entity => (
            <p className={'text-white'} key={entity.id}>
              {`${entity.id} : ${entity.name}`}
            </p>
          ))}
      </>
    )
  }

  /**
   * Creates a paragraph of scenes.
   * @private
   */
  private getScenes(): React.ReactNode {
    return (
      <>
        {getScenes()
          .sort((a, b) => a.id - b.id)
          .map(scene => (
            <p className={'text-white'} key={scene.id}>
              {`${scene.id} : ${scene.identifier} [${scene.type}]`}
            </p>
          ))}
      </>
    )
  }

  /**
   * Creates a paragraph of quests.
   * @private
   */
  private getQuests(): React.ReactNode {
    return (
      <>
        {listQuests()
          .sort((a, b) => a.id - b.id)
          .map(quest => (
            <p className={'text-white'} key={quest.id}>
              {`${quest.id} : ${getMainQuestFor(quest)?.title ?? 'Unknown'} - ${quest.description}`}
            </p>
          ))}
      </>
    )
  }

  render() {
    return (
      <div className={'m-[12px_5px_0_12px] overflow-auto'}>
        <p className={'text-white'}>
          // Grasscutter 3.6.0 GM Handbook
          <br />
          // Generated by the HTML GM Handbook.
          <br />
          <br />
          <br />
          // Commands
        </p>

        {this.getCommands()}

        <p className={'text-white'}>
          <br />
          <br />
          // Avatars
        </p>

        {this.getAvatars()}

        <p className={'text-white'}>
          <br />
          <br />
          // Items
        </p>

        {this.getItems()}

        <p className={'text-white'}>
          <br />
          <br />
          // Monsters
        </p>

        {this.getMonsters()}

        <p className={'text-white'}>
          <br />
          <br />
          // Scenes
        </p>

        {this.getScenes()}

        <p className={'text-white'}>
          <br />
          <br />
          // Quests
        </p>

        {this.getQuests()}
      </div>
    )
  }
}

export default PlainText
